(() => {
 const dialog=document.createElement('dialog');dialog.className='research-dialog shared-research';dialog.setAttribute('data-lenis-prevent','');dialog.setAttribute('aria-labelledby','shared-research-title');
 dialog.innerHTML='<div class="dialog-bar"><span>FIELD NOTE / 水の仕組み</span><button type="button" class="dialog-close" aria-label="解説を閉じる">閉じる ×</button></div><div class="dialog-content"><p class="dialog-kicker"></p><h2 id="shared-research-title"></h2><p class="dialog-explain"></p><div class="research-links"></div><p class="dialog-note"></p></div>';
 document.body.append(dialog);
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');let origin=null,motion=null,closing=false;
 function close(){if(closing||!dialog.open)return;closing=true;motion?.cancel();const done=()=>{dialog.close();document.documentElement.classList.remove('research-open');window.waterScroller?.start();origin?.focus({preventScroll:true});closing=false;};if(reduced.matches)done();else{motion=dialog.animate([{opacity:1},{opacity:0}],{duration:200,easing:'ease-in'});motion.onfinish=done;}}
 dialog.querySelector('button').addEventListener('click',close);dialog.addEventListener('cancel',e=>{e.preventDefault();close()});dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))close()});
 window.researchPanel={dialog,open(trigger,data,event){if(dialog.open)return;origin=trigger;motion?.cancel();dialog.querySelector('.dialog-kicker').textContent=data.kicker;dialog.querySelector('h2').textContent=data.title;dialog.querySelector('.dialog-explain').textContent=data.explain;dialog.querySelector('.dialog-note').textContent=data.note;const links=dialog.querySelector('.research-links');links.replaceChildren();data.papers.forEach(p=>{const a=document.createElement('a');a.href=p.href;const title=document.createElement('strong');title.textContent=p.title;const meta=document.createElement('small');meta.textContent=p.meta||'研究をもとにした日本語の解説';const action=document.createElement('span');action.textContent='解説を読む →';a.append(title,meta);for(const [cls,value] of [["evidence-meaning",p.meaning],["evidence-scope",p.scope]]){if(value){const text=document.createElement("p");text.className=cls;text.textContent=value;a.append(text);}}a.append(action);links.append(a)});window.waterScroller?.stop();document.documentElement.classList.add('research-open');dialog.showModal();dialog.scrollTop=0;if(!reduced.matches&&event?.detail!==0)motion=dialog.animate([{opacity:0,transform:'translateY(16px)'},{opacity:1,transform:'translateY(0)'}],{duration:300,easing:'cubic-bezier(0.215,0.61,0.355,1)'});},decorate(trigger,label){trigger.classList.add('research-cta');trigger.setAttribute('aria-haspopup','dialog');trigger.replaceChildren(document.createTextNode(label));const icon=document.createElement('span');icon.setAttribute('aria-hidden','true');icon.textContent='›';trigger.append(icon);}};
})();
